title: Manuela's Blog on NEO CITY USA
author: Manuela M.
email: mmensah.ptech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello everyone and welcome to my page, this may seem new and different to all of you.
  I decided to discuss and post pictures about NCT being on the NEO CITY USA tour!!
# social links
twitter_username: @NCTsmtown_127
github_username:  manuela

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
